//! Every check preflight knows about, listed once.
//!
//! Deliberately plain struct literals rather than a macro. This is the file a
//! sceptical operator reads to see exactly what the tool will look at, so it
//! stays greppable and boring.

use crate::{
    checks::{arg, fs, hw, kernel, xdp},
    model::{Check, ClientKind::*, Layer, Profile::*, Severity::*},
};

const AGAVE: &[crate::model::ClientKind] = &[AgaveValidator];
const ANY_VALIDATOR: &[crate::model::ClientKind] = &[AgaveValidator, TestValidator];

const ANY_CLIENT: &[crate::model::ClientKind] =
    &[AgaveValidator, TestValidator, Firedancer, Unknown];

pub static CHECKS: &[Check] = &[
    // HW and KRN describe the host, not a validator, so they run on a bare box.
    Check {
        id: "PF-HW-0001",
        layer: Layer::Hw,
        severity: Fatal,
        title: "CPU architecture is x86-64",
        profiles: &[Testnet, Mainnet],
        clients: ANY_CLIENT,
        needs_root: false,
        reports_only: false,
        source: hw::S_REQ,
        run: hw::architecture,
    },
    Check {
        id: "PF-HW-0002",
        layer: Layer::Hw,
        severity: Fatal,
        title: "CPU supports AVX2",
        profiles: &[Testnet, Mainnet],
        clients: ANY_CLIENT,
        needs_root: false,
        reports_only: false,
        source: hw::S_REQ,
        run: hw::avx2,
    },
    Check {
        id: "PF-HW-0003",
        layer: Layer::Hw,
        severity: Degraded,
        title: "CPU base clock is 2.8 GHz or faster",
        profiles: &[Testnet, Mainnet],
        clients: ANY_CLIENT,
        needs_root: false,
        reports_only: false,
        source: hw::S_REQ,
        run: hw::base_clock,
    },
    Check {
        id: "PF-HW-0004",
        layer: Layer::Hw,
        severity: Advisory,
        title: "CPU core and thread count",
        profiles: &[Testnet, Mainnet],
        clients: ANY_CLIENT,
        needs_root: false,
        reports_only: true,
        source: hw::S_REQ,
        run: hw::cores,
    },
    Check {
        id: "PF-HW-0005",
        layer: Layer::Hw,
        severity: Degraded,
        title: "Installed memory",
        profiles: &[Local, Testnet, Mainnet],
        clients: ANY_CLIENT,
        needs_root: false,
        reports_only: true,
        source: hw::S_REQ,
        run: hw::memory,
    },
    Check {
        id: "PF-FS-0001",
        layer: Layer::Fs,
        severity: Degraded,
        title: "Storage against Anza's published sizes",
        profiles: &[Testnet, Mainnet],
        clients: ANY_CLIENT,
        needs_root: false,
        reports_only: false,
        source: fs::S_REQ,
        run: fs::capacity,
    },
    Check {
        id: "PF-FS-0002",
        layer: Layer::Fs,
        severity: Degraded,
        title: "Accounts and ledger on separate devices",
        profiles: &[Testnet, Mainnet],
        clients: ANY_CLIENT,
        needs_root: false,
        reports_only: false,
        source: fs::S_REQ,
        run: fs::separate_devices,
    },
    Check {
        id: "PF-FS-0003",
        layer: Layer::Fs,
        severity: Degraded,
        title: "Storage is solid-state and local",
        profiles: &[Testnet, Mainnet],
        clients: ANY_CLIENT,
        needs_root: false,
        reports_only: false,
        source: fs::S_REQ,
        run: fs::storage_media,
    },
    Check {
        id: "PF-FS-0004",
        layer: Layer::Fs,
        severity: Advisory,
        title: "noatime on validator filesystems",
        profiles: &[Testnet, Mainnet],
        clients: ANY_CLIENT,
        needs_root: false,
        reports_only: false,
        source: fs::S_OPERATOR,
        run: fs::noatime,
    },
    Check {
        id: "PF-FS-0005",
        layer: Layer::Fs,
        severity: Advisory,
        title: "Filesystem is ext4 or xfs",
        profiles: &[Testnet, Mainnet],
        clients: ANY_CLIENT,
        needs_root: false,
        reports_only: false,
        source: fs::S_REQ,
        run: fs::filesystem_type,
    },
    Check {
        id: "PF-FS-0006",
        layer: Layer::Fs,
        severity: Degraded,
        title: "Accounts filesystem supports direct I/O",
        profiles: &[Testnet, Mainnet],
        clients: ANY_CLIENT,
        needs_root: false,
        reports_only: false,
        source: fs::S_DIO,
        run: fs::direct_io_support,
    },
    Check {
        id: "PF-KRN-0001",
        layer: Layer::Kernel,
        severity: Fatal,
        title: "net.core.rmem_max",
        profiles: &[Local, Testnet, Mainnet],
        clients: ANY_CLIENT,
        needs_root: false,
        reports_only: false,
        source: kernel::S_LIMITS,
        run: kernel::rmem_max,
    },
    Check {
        id: "PF-KRN-0002",
        layer: Layer::Kernel,
        severity: Fatal,
        title: "net.core.wmem_max",
        profiles: &[Local, Testnet, Mainnet],
        clients: ANY_CLIENT,
        needs_root: false,
        reports_only: false,
        source: kernel::S_LIMITS,
        run: kernel::wmem_max,
    },
    Check {
        id: "PF-KRN-0003",
        layer: Layer::Kernel,
        severity: Fatal,
        title: "vm.max_map_count",
        profiles: &[Local, Testnet, Mainnet],
        clients: ANY_CLIENT,
        needs_root: false,
        reports_only: false,
        source: kernel::S_LIMITS,
        run: kernel::max_map_count,
    },
    Check {
        id: "PF-KRN-0004",
        layer: Layer::Kernel,
        severity: Fatal,
        title: "fs.nr_open",
        profiles: &[Local, Testnet, Mainnet],
        clients: ANY_CLIENT,
        needs_root: false,
        reports_only: false,
        source: kernel::S_NR_OPEN,
        run: kernel::nr_open,
    },
    Check {
        id: "PF-ARG-0001",
        layer: Layer::Arg,
        severity: Fatal,
        title: "Dynamic port range is wide enough",
        profiles: &[Testnet, Mainnet],
        clients: AGAVE,
        needs_root: false,
        reports_only: false,
        source: arg::S_PORTS,
        run: arg::port_range,
    },
    Check {
        id: "PF-ARG-0002",
        layer: Layer::Arg,
        severity: Fatal,
        title: "Private addressing requires --no-xdp",
        profiles: &[Local, Testnet, Mainnet],
        clients: AGAVE,
        needs_root: false,
        reports_only: false,
        source: arg::S_XDP_PRIV,
        run: arg::private_addr_xdp,
    },
    Check {
        id: "PF-ARG-0003",
        layer: Layer::Arg,
        severity: Fatal,
        title: "No arguments removed in v4.0",
        profiles: &[Local, Testnet, Mainnet],
        clients: ANY_VALIDATOR,
        needs_root: false,
        reports_only: false,
        source: arg::S_REMOVED_40,
        run: arg::removed_in_40,
    },
    Check {
        id: "PF-ARG-0004",
        layer: Layer::Arg,
        severity: Fatal,
        title: "Block verification method is supported",
        profiles: &[Testnet, Mainnet],
        clients: AGAVE,
        needs_root: false,
        reports_only: false,
        source: arg::S_BVM,
        run: arg::block_verification_method,
    },
    Check {
        id: "PF-ARG-0005",
        layer: Layer::Arg,
        severity: Degraded,
        title: "Block production method is supported",
        profiles: &[Testnet, Mainnet],
        clients: AGAVE,
        needs_root: false,
        reports_only: false,
        source: arg::S_BPM,
        run: arg::block_production_method,
    },
    Check {
        id: "PF-ARG-0006",
        layer: Layer::Arg,
        severity: Degraded,
        title: "No deprecated experimental XDP flags",
        profiles: &[Testnet, Mainnet],
        clients: AGAVE,
        needs_root: false,
        reports_only: false,
        source: arg::S_XDP_DEP,
        run: arg::deprecated_xdp_flags,
    },
    Check {
        id: "PF-ARG-0007",
        layer: Layer::Arg,
        severity: Degraded,
        title: "PoH pinned core flag uses the current name",
        profiles: &[Testnet, Mainnet],
        clients: AGAVE,
        needs_root: false,
        reports_only: false,
        source: arg::S_POH,
        run: arg::deprecated_poh_flag,
    },
    Check {
        id: "PF-ARG-0008",
        layer: Layer::Arg,
        severity: Degraded,
        title: "No deprecated accounts-db arguments",
        profiles: &[Testnet, Mainnet],
        clients: AGAVE,
        needs_root: false,
        reports_only: false,
        source: arg::S_ADB,
        run: arg::deprecated_accounts_db,
    },
    Check {
        id: "PF-ARG-0009",
        layer: Layer::Arg,
        severity: Degraded,
        title: "Accounts index limit is set explicitly",
        profiles: &[Testnet, Mainnet],
        clients: AGAVE,
        needs_root: false,
        reports_only: false,
        source: arg::S_INDEX,
        run: arg::accounts_index_limit,
    },
    Check {
        id: "PF-ARG-0010",
        layer: Layer::Arg,
        severity: Degraded,
        title: "Direct I/O setting matches the accounts filesystem",
        profiles: &[Testnet, Mainnet],
        clients: AGAVE,
        needs_root: false,
        reports_only: false,
        source: arg::S_DIO,
        run: arg::direct_io,
    },
    Check {
        id: "PF-ARG-0011",
        layer: Layer::Arg,
        severity: Degraded,
        title: "Ledger size limit uses the current flag",
        profiles: &[Testnet, Mainnet],
        clients: AGAVE,
        needs_root: false,
        reports_only: false,
        source: arg::S_43_LEDGER,
        run: arg::limit_ledger_size,
    },
    Check {
        id: "PF-ARG-0012",
        layer: Layer::Arg,
        severity: Advisory,
        title: "Banking trace flag still expresses something",
        profiles: &[Testnet, Mainnet],
        clients: AGAVE,
        needs_root: false,
        reports_only: false,
        source: arg::S_43_TRACE,
        run: arg::disable_banking_trace,
    },
    Check {
        id: "PF-ARG-0013",
        layer: Layer::Arg,
        severity: Fatal,
        title: "No removed TPU connection pool argument",
        profiles: &[Testnet, Mainnet],
        clients: AGAVE,
        needs_root: false,
        reports_only: false,
        source: arg::S_43_POOL,
        run: arg::tpu_connection_pool_size,
    },
    Check {
        id: "PF-XDP-0001",
        layer: Layer::Xdp,
        severity: Fatal,
        title: "XDP capabilities are in the permitted set",
        profiles: &[Local, Testnet, Mainnet],
        clients: AGAVE,
        needs_root: false,
        reports_only: false,
        source: xdp::S_CAPS,
        run: xdp::capabilities,
    },
    Check {
        id: "PF-XDP-0007",
        layer: Layer::Xdp,
        severity: Degraded,
        title: "Capabilities come from the unit, not from setcap",
        profiles: &[Testnet, Mainnet],
        clients: AGAVE,
        needs_root: true,
        reports_only: false,
        source: xdp::S_CAP_PERSIST,
        run: xdp::capability_persistence,
    },
];

pub fn find(id: &str) -> Option<&'static Check> {
    CHECKS.iter().find(|c| c.id.eq_ignore_ascii_case(id))
}
